name = "g-omid-dev"
main = "./index.js"
routes = [
	{ pattern = "go.omid.dev", custom_domain = true, zone_name = "omid.dev" }
]
account_id = "7a7dc686e71a3092b4275d55e6d518d3"
usage_model = "bundled"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-11-19"
node_compat = true
kv_namespaces = [
    { binding = "SHORTLINKS", id = "4573a71d96864448827691a72b552de9", preview_id = "5cc9d481707349438fca44a0a1b4665d" }
]
[vars]
SECRET_SIGNATURE = "af68d7e176"
